apiVersion: v1
kind: Service
metadata:
  name: mysql-transkrip
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 33006
  selector:
    app: mysql-transkrip
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-transkrip
spec:
  selector:
    matchLabels:
      app: mysql-transkrip
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-transkrip
    spec:
      containers:
      - image: 192.168.56.101:5000/mysql:5.7.26
        name: mysql-transkrip
        env:
          # Use secret in real usage or production
        - name: MYSQL_ROOT_PASSWORD
          value: P@ssw0rd
        - name: MYSQL_DATABASE
          value: transkrip_nilai
        - name: MYSQL_USER
          value: whamdani
        - name: MYSQL_PASSWORD
          value: P@ssw0rd
        ports:
        - containerPort: 3306
          name: mysql-transkrip
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
